spring:
  application:
    name: onm-apigw
  profiles:
    active: local
  banner: 
    location: "classpath:app-banner.txt"
    
    
## logging
logging: 
  level:
    org.springframework.cloud.gateway: info
    com.sk.signet: info
    root: info